export const mockGraphData = {
  nodes: [
    // --- Architecture ---
    {
      id: 'Transformer',
      label: 'Transformer',
      group: 'Architecture',
      size: 45,
      confidence: 0.98,
      source_type: 'paper',
      source: 'Attention Is All You Need (2017)',
      url: 'https://arxiv.org/abs/1706.03762',
      info: 'A model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output.',
    },
    {
      id: 'BERT',
      label: 'BERT',
      group: 'Architecture',
      size: 40,
      confidence: 0.95,
      source_type: 'paper',
      source: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
      url: 'https://arxiv.org/abs/1810.04805',
      info: 'Bidirectional Encoder Representations from Transformers.',
    },
    {
      id: 'GPT-3',
      label: 'GPT-3',
      group: 'Architecture',
      size: 42,
      confidence: 0.92,
      source_type: 'paper',
      source: 'Language Models are Few-Shot Learners',
      url: 'https://arxiv.org/abs/2005.14165',
      info: 'A state-of-the-art language model with 175 billion parameters.',
    },
    {
      id: 'ResNet',
      label: 'ResNet',
      group: 'Architecture',
      size: 35,
      confidence: 0.88,
      source_type: 'paper',
      source: 'Deep Residual Learning for Image Recognition',
      url: 'https://arxiv.org/abs/1512.03385',
      info: 'Introduced residual connections to allow training of very deep networks.',
    },
    {
      id: 'LSTM',
      label: 'LSTM',
      group: 'Architecture',
      size: 30,
      confidence: 0.85,
      source_type: 'textbook',
      source: 'Deep Learning (Goodfellow et al.)',
      url: '',
      info: 'Long Short-Term Memory networks are a special kind of RNN, capable of learning long-term dependencies.',
    },
    {
      id: 'CNN',
      label: 'CNN',
      group: 'Architecture',
      size: 38,
      confidence: 0.90,
      source_type: 'textbook',
      source: 'Deep Learning (Goodfellow et al.)',
      url: '',
      info: 'Convolutional Neural Networks, specialized for processing grid-like data such as images.',
    },

    // --- Optimization ---
    {
      id: 'Adam',
      label: 'Adam',
      group: 'Optimization',
      size: 25,
      confidence: 0.94,
      source_type: 'paper',
      source: 'Adam: A Method for Stochastic Optimization',
      url: 'https://arxiv.org/abs/1412.6980',
      info: 'An algorithm for first-order gradient-based optimization of stochastic objective functions.',
    },
    {
      id: 'SGD',
      label: 'SGD',
      group: 'Optimization',
      size: 28,
      confidence: 0.96,
      source_type: 'textbook',
      source: 'Deep Learning (Goodfellow et al.)',
      url: '',
      info: 'Stochastic Gradient Descent, the backbone of training neural networks.',
    },
    {
      id: 'Backprop',
      label: 'Backpropagation',
      group: 'Optimization',
      size: 35,
      confidence: 0.99,
      source_type: 'textbook',
      source: 'Pattern Recognition and Machine Learning (Bishop)',
      url: '',
      info: 'The primary algorithm for computing gradients in neural networks.',
    },
    {
      id: 'Dropout',
      label: 'Dropout',
      group: 'Optimization',
      size: 25,
      confidence: 0.89,
      source_type: 'paper',
      source: 'Dropout: A Simple Way to Prevent Neural Networks from Overfitting',
      url: 'https://jmlr.org/papers/v15/srivastava14a.html',
      info: 'A regularization technique for reducing overfitting in neural networks.',
    },

    // --- History ---
    {
      id: 'Perceptron',
      label: 'Perceptron',
      group: 'History',
      size: 20,
      confidence: 0.80,
      source_type: 'textbook',
      source: 'Neural Networks for Pattern Recognition',
      url: '',
      info: 'The simplest type of feedforward neural network classifier.',
    },
    {
      id: 'TuringTest',
      label: 'Turing Test',
      group: 'History',
      size: 22,
      confidence: 0.82,
      source_type: 'paper',
      source: 'Computing Machinery and Intelligence (1950)',
      url: '',
      info: 'A test of a machine\'s ability to exhibit intelligent behavior equivalent to, or indistinguishable from, that of a human.',
    },

    // --- Hardware ---
    {
      id: 'GPU',
      label: 'GPU',
      group: 'Hardware',
      size: 32,
      confidence: 0.91,
      source_type: 'textbook',
      source: 'Computer Architecture: A Quantitative Approach',
      url: '',
      info: 'Graphics Processing Unit, essential for parallel processing in Deep Learning.',
    },
    {
      id: 'TPU',
      label: 'TPU',
      group: 'Hardware',
      size: 30,
      confidence: 0.88,
      source_type: 'paper',
      source: 'In-Datacenter Performance Analysis of a Tensor Processing Unit',
      url: 'https://arxiv.org/abs/1704.04760',
      info: 'Tensor Processing Unit, an AI accelerator application-specific integrated circuit (ASIC) developed by Google.',
    },
    
    // --- Concepts ---
    {
      id: 'Attention',
      label: 'Attention Mechanism',
      group: 'Architecture',
      size: 36,
      confidence: 0.93,
      source_type: 'paper',
      source: 'Neural Machine Translation by Jointly Learning to Align and Translate',
      url: 'https://arxiv.org/abs/1409.0473',
      info: 'Allows the model to focus on different parts of the input sequence when producing the output.',
    },
     {
      id: 'GeoffreyHinton',
      label: 'Geoffrey Hinton',
      group: 'History',
      size: 28,
      confidence: 0.95,
      source_type: 'textbook',
      source: 'The Deep Learning Revolution',
      url: '',
      info: 'Cognitive psychologist and computer scientist, most noted for his work on artificial neural networks.',
    },
  ],
  links: [
    { source: 'Transformer', target: 'Attention', relation: 'USES', desc: 'Transformer utilizes self-attention layers.' },
    { source: 'BERT', target: 'Transformer', relation: 'EVOLVED_FROM', desc: 'BERT is based on the Transformer architecture.' },
    { source: 'GPT-3', target: 'Transformer', relation: 'EVOLVED_FROM', desc: 'GPT models utilize the Transformer decoder stack.' },
    { source: 'Transformer', target: 'LSTM', relation: 'REPLACES', desc: 'Transformers largely replaced RNN/LSTMs in NLP.' },
    { source: 'ResNet', target: 'CNN', relation: 'EVOLVED_FROM', desc: 'ResNet is a specific type of CNN.' },
    { source: 'Adam', target: 'SGD', relation: 'EVOLVED_FROM', desc: 'Adam combines ideas from RMSProp and Momentum (related to SGD).' },
    { source: 'Backprop', target: 'GeoffreyHinton', relation: 'PROPOSED_BY', desc: 'Popularized by Hinton et al.' },
    { source: 'Dropout', target: 'GeoffreyHinton', relation: 'PROPOSED_BY', desc: 'Co-authored by Hinton.' },
    { source: 'CNN', target: 'GPU', relation: 'ACCELERATED_BY', desc: 'CNN training is highly efficient on GPUs.' },
    { source: 'Transformer', target: 'TPU', relation: 'ACCELERATED_BY', desc: 'TPUs were designed to accelerate Transformer workloads.' },
    { source: 'Perceptron', target: 'Backprop', relation: 'LACKS', desc: 'Single layer perceptrons cannot use backprop for hidden layers.' },
    { source: 'LSTM', target: 'Backprop', relation: 'TRAINED_WITH', desc: 'LSTMs are trained using Backpropagation Through Time.' },
    { source: 'CNN', target: 'Backprop', relation: 'TRAINED_WITH', desc: 'Standard training method for CNNs.' },
    { source: 'Transformer', target: 'Adam', relation: 'OPTIMIZED_BY', desc: 'Adam is the standard optimizer for Transformers.' },
  ]
};
